package main

import (
	"fmt"
	"os"
	"reflect"
	"regexp"
	"sort"
	"strings"
	"text/template"
)

var (
	re = regexp.MustCompile(`\{(\w+)}`)
	// 正则表达式
	routeRegex = regexp.MustCompile(`@Router\s+(\S+)\s+\[(\w+)\]`)
	//descRegex       = regexp.MustCompile(`@Desc\s+(.+)`)
	groupRegex = regexp.MustCompile(`@Group\s+(.+)`)
	//rolesRegex      = regexp.MustCompile(`@Roles\s+([^\s]+)`)
	//permissionRegex = regexp.MustCompile(`@Permission\s+([^\s]+)`)
)

// GinTemplateData 定义一个结构体，用来填充模板
type GinTemplateData struct {
	ProjectName string
}

type Route struct {
	HTTPMethod  string
	Path        string
	Func        string
	PackagePath string
	PackageName string
}

type TemplateRoute struct {
	Group   string
	Method  string
	Path    string
	Handler string
}

type GroupedRouters struct {
	GroupName string
	Routers   []TemplateRoute
}

type TemplateData struct {
	Imports []string
	Groups  []string
	Grouped []GroupedRouters
}

const routeTemplate = `// Code generated by build tool. DO NOT EDIT.

package routers

import (
{{- range .Imports }}
	"{{ . }}"
{{- end }}
	"github.com/gin-gonic/gin"
)

type routeGroup struct {
{{- range .Groups }}
	{{ . }} *gin.RouterGroup
{{- end }}
}

func (r *routeGroup) register() {
{{- range $gIndex, $group := .Grouped }}
{{- range $group.Routers }}
	r.{{ .Group }}.{{ .Method }}("{{ .Path }}", {{ .Handler }})
{{- end }}
{{- if lt $gIndex (sub1 (len $.Grouped)) }}
{{ end }}
{{- end }}
}`

const gitignore = `# If you prefer the allow list template instead of the deny list, see community template:
# https://github.com/github/gitignore/blob/main/community/Golang/Go.AllowList.gitignore
#
# Binaries for programs and plugins
.idea
*.exe
*.exe~
*.dll
*.so
*.upx
*.dylib

logs
tmp
demo
test

# Test binary, built with 'go test -c'
*.test

# Output of the go coverage tool, specifically when used with LiteIDE
*.out

# Dependency directories (remove the comment below to include it)
vendor

# Go workspace file
go.work
go.work.sum

*.db
data
*.sqlite`

func writeRouters(routers map[string][]Route) error {
	funcMap := template.FuncMap{
		"len":  func(v interface{}) int { return reflect.ValueOf(v).Len() },
		"sub1": func(i int) int { return i - 1 },
	}

	tmpl, err := template.New("routers").Funcs(funcMap).Parse(routeTemplate)
	if err != nil {
		return fmt.Errorf("解析模板失败: %w", err)
	}

	// 收集 import、分组、组内路由
	importSet := make(map[string]struct{})
	var groups []string
	groupMap := make(map[string][]TemplateRoute)

	for groupName, routeList := range routers {
		groups = append(groups, groupName)
		for _, route := range routeList {
			importSet[route.PackagePath] = struct{}{}
			groupMap[groupName] = append(groupMap[groupName], TemplateRoute{
				Group:   groupName,
				Method:  strings.ToUpper(route.HTTPMethod),
				Path:    route.Path,
				Handler: fmt.Sprintf("%s.%s", route.PackageName, route.Func),
			})
		}
	}
	sort.Strings(groups)

	var imports []string
	for path := range importSet {
		imports = append(imports, path)
	}
	sort.Strings(imports)

	var grouped []GroupedRouters
	for _, g := range groups {
		grouped = append(grouped, GroupedRouters{
			GroupName: g,
			Routers:   groupMap[g],
		})
	}

	data := TemplateData{
		Imports: imports,
		Groups:  groups,
		Grouped: grouped,
	}

	routerPath := "routers/router.go"
	// 判断 routers 文件夹是否存在，不存在则创建
	if !IsDirExist("routers") {
		if err = os.Mkdir("routers", os.ModePerm); err != nil {
			return fmt.Errorf("创建 routers 文件夹失败: %w", err)
		}
	}

	// 输出
	f, err := os.Create(routerPath)
	if err != nil {
		return fmt.Errorf("创建文件失败: %w", err)
	}
	defer f.Close()

	if err := tmpl.Execute(f, data); err != nil {
		return fmt.Errorf("执行模板失败: %w", err)
	}

	fmt.Println("✅ 路由文件生成成功:", routerPath)
	return nil
}
