// Code generated by build tool. DO NOT EDIT.

package routers

import (
	"buildx/internal/bootstrap"
	"github.com/gin-gonic/gin"
	"gorm.io/gorm"
)

type routeGroup struct {
	public *gin.RouterGroup
}

func (r *routeGroup) register(db *gorm.DB) {
	// 初始化仓库和服务
	ctx := bootstrap.NewAppContext(db)
	r.public.GET("/list/users", ctx.IndexHandler.ListIndexs)
	r.public.GET("/disable_all/user", ctx.IndexHandler.DisableAllIndexs)
}